# Generated by Django 4.1.5 on 2023-01-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumAccount',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('keystore', models.TextField()),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
        ),
    ]
