# Generated by Django 4.1.5 on 2023-01-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eth2web', '0003_ethereumblock_alter_ethereumaccount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
