# Generated by Django 4.1.5 on 2023-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth2web', '0004_alter_ethereumaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumblock',
            name='timestamp',
            field=models.CharField(max_length=25),
        ),
    ]
